title: Ravi teja Salendra
logo: /assets/img/raviteja.jpeg
description: As a Backend Developer, I contributed to multiple backend and DevOps-facing projects. My core tech stack included Java, Spring Boot with hands-on involvement in version control (Git) and microservices.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
